class WatchList:
    ALL = "All"
    FAVORITES = "Favorites"
    TOP_PICKS = "Top Picks"
    TOP_GAINER = "Top Gainer"
    TOP_LOSER = "Top Loser"
    SHARES = "Shares"
    FOREX = "Forex"
    INDEX = "index"
    COMMODITIES = "Commodities"
    CRYPTO = "Crypto"
